---
# key-auth

- name: Get list of authentication credential configs for consumer | {{ outer_item.name }}
  uri:
    url: "{{ kong_admin_api_url }}/consumers/{{ kong_consumer_config.username }}/{{ outer_item.name }}"
  register: current_key_auth_creds

#- debug: var=current_key_auth_creds

- name: Create authentication credentials for consumer | {{ outer_item.name }}
  uri:
     url:    "{{ kong_admin_api_url }}/consumers/{{ kong_consumer_config.username }}/{{ outer_item.name }}"
     body:   "{{  outer_item.parameters }}"
     method: POST
     status_code: 201
     body_format: json
  register: created
  when: not outer_item.parameters.key in current_key_auth_creds.json.data|map(attribute='key')|list

- name: Get authentication credentials id | {{ outer_item.name }}
  template:
    src:  consumer_auth_id.j2
    dest: /tmp/{{ outer_item.name }}_{{ item.key }}.id
  with_items: "{{ current_key_auth_creds.json.data|default([]) }}"
  delegate_to: 127.0.0.1
  become: false

- name: Update authentication credentials for consumer | {{ outer_item.name }}
  uri:
     url:    "{{ kong_admin_api_url }}/consumers/{{ kong_consumer_config.username }}/{{ outer_item.name }}/{{ lookup('file','/tmp/' + outer_item.name + '_' + outer_item.parameters.key + '.id') }}"
     body:   "{{  outer_item.parameters }}"
     method: PATCH
     status_code: 200
     body_format: json
  register: updated
  when: outer_item.parameters.key in current_key_auth_creds.json.data|map(attribute='key')|list

- name: Identify authentication credentials configs for key-auth
  set_fact: key={{ item.parameters.key }}
  with_items: "{{ kong_consumer_config.plugins }}"
  register: r_key_auth
  when: item.name == outer_item.name

- name: Set list of keys
  set_fact: key_auth_keys="{{ r_key_auth.results|selectattr('ansible_facts', 'defined')|map(attribute='ansible_facts.key')|list }}"

- name: Delete authentication credentials for consumer | {{ outer_item.name }}
  uri:
     url:    "{{ kong_admin_api_url }}/consumers/{{ kong_consumer_config.username }}/{{ outer_item.name }}/{{ lookup('file','/tmp/' + outer_item.name + '_' + item.key + '.id') }}"
     method: DELETE
     status_code: 204
  with_items: "{{ current_key_auth_creds.json.data|default([]) }}"
  register: deleted
  when: not item.key in key_auth_keys
